Net Core/AyumuBook/AyumuBookWeb/Models/Category.cs
using MvcContrib.UI.InputBuilder.Attributes;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace AyumuBookWeb.Models
{
    public class Category
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [DisplayName("DisplayOrder")]
        [Range(1,100,ErrorMessage = "No puede superar de 100")]
        public int DisplayOrder { get; set; }
        public DateTime CreatedDateTime { get; set; } = DateTime.Now;
    }
}

Net Core/AyumuBook/AyumuBookWeb/Models/ErrorViewModel.cs
namespace AyumuBookWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Net Core/AyumuBook/AyumuBookWeb/Controllers/CategoryController.cs
using AyumuBookWeb.Data;
using AyumuBookWeb.Models;
using Microsoft.AspNetCore.Mvc;

namespace AyumuBookWeb.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _db;
        public CategoryController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Category> objCategoria = _db.Categoriee.ToList();
            return View(objCategoria);
        }
        //Get
        public IActionResult Create()
        {
            return View();
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category categoryObj)
        {
            if(categoryObj.Name == categoryObj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("CustomError", "La orden no puede ser exacto como el nombre");
            }
            if (ModelState.IsValid)
            {
                _db.Categoriee.Add(categoryObj);
                _db.SaveChanges();
                TempData["sucess"] = "Categoria Creado";
                return RedirectToAction("Index");
            }
            return View(categoryObj);
        }


        //Edit
        public IActionResult Edit(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }
            var categoryId = _db.Categoriee.Find(id);
            if(categoryId == null)
            {
                return NotFound();
            }
            return View(categoryId);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category categoryObj)
        {
            if (categoryObj.Name == categoryObj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("CustomError", "La orden no puede ser exacto como el nombre");
            }
            if (ModelState.IsValid)
            {
                _db.Categoriee.Update(categoryObj);
                _db.SaveChanges();
                TempData["sucess"] = "Categoria actualizada";
                return RedirectToAction("Index");
            }
            return View(categoryObj);
        }

        //Delete
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryId = _db.Categoriee.Find(id);
            if (categoryId == null)
            {
                return NotFound();
            }
            return View(categoryId);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Category categoryObj)
        {
            if (categoryObj.Name == categoryObj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("CustomError", "La orden no puede ser exacto como el nombre");
            }
            if (ModelState.IsValid)
            {
                _db.Categoriee.Remove(categoryObj);
                _db.SaveChanges();
                TempData["error"] = "Categoria Eliminada";
                return RedirectToAction("Index");
            }
            return View(categoryObj);
        }
    }
}

Net Core/AyumuBook/AyumuBookWeb/Controllers/HomeController.cs
using AyumuBookWeb.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AyumuBookWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Net Core/AyumuBook/AyumuBookWeb/Views/Category/Create.cshtml
@model Category

<form method="post" asp-action="Create">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Creando Categoria</h2>
            <hr />
        </div>
        @*<div asp-validation-summary="All" ></div>*@
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="DisplayOrder"></label>
            <input asp-for="DisplayOrder" class="form-control"/>
            <span asp-validation-for="DisplayOrder" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" >Crear</button>
        <a asp-controller="Category" asp-action="Index" class="btn btn-secondary">Regresar</a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Net Core/AyumuBook/AyumuBookWeb/Views/Category/Delete.cshtml
@model Category

<form method="post" asp-action="Delete">
    
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Eliminando Categoria</h2>
            <hr />
        </div>
        @*<div asp-validation-summary="All" ></div>*@
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name"  class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="DisplayOrder"></label>
            <input asp-for="DisplayOrder"  class="form-control"/>
            <span asp-validation-for="DisplayOrder" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-danger" >Eliminar</button>
        <a asp-controller="Category" asp-action="Index" class="btn btn-secondary">Regresar</a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Net Core/AyumuBook/AyumuBookWeb/Views/Category/Edit.cshtml
@model Category

<form method="post">
    <div class="border p-3 mt-4" action="Edit">
        <div class="row pb-2">
            <h2 class="text-primary">Editando Categoria</h2>
            <hr />
        </div>
        @*<div asp-validation-summary="All" ></div>*@
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="DisplayOrder"></label>
            <input asp-for="DisplayOrder" class="form-control"/>
            <span asp-validation-for="DisplayOrder" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" >Actualizar</button>
        <a asp-controller="Category" asp-action="Index" class="btn btn-secondary">Regresar</a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Net Core/AyumuBook/AyumuBookWeb/Views/Category/Index.cshtml
@model IEnumerable<Category>
@{
    ViewData["Title"] = "Index";
}

<partial name="_Notificacion" />

<h1>Index Categoty</h1>
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2>Listado de Categoria</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Category" asp-action="Create" class="btn btn-primary">Crear una nueva categoria</a>
        </div>
    </div>
    <br /><br />


    <table class="table table-bordered table-striped" style="width=100%">
        <thead>
            <tr>
                <th>Nombre Categoria</th>
                <th>Ordenes</th>
                <th>Accion</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var obj in Model)
            {
                <tr>
                    <td width="50%">@obj.Name</td>
                    <td width="30%">@obj.DisplayOrder</td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a class="btn btn-warning" asp-controller="Category" asp-action="Edit" asp-route-id="@obj.Id">Editar</a>
                            <a class="btn btn-danger ms-2" asp-controller="Category" asp-action="Delete" asp-route-id="@obj.Id">Eliminar</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Net Core/AyumuBook/AyumuBookWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Net Core/AyumuBook/AyumuBookWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AyumuBookWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AyumuBookWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AyumuBookWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AyumuBookWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Net Core/AyumuBook/AyumuBookWeb/Views/Shared/_Notificacion.cshtml
@if (TempData["sucess"] != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>@TempData["sucess"] 
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>

}
@if (TempData["error"] != null)
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>@TempData["error"] 
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}